<?xml version="1.0" encoding="UTF-8"?>

<!--
  * conferenceSettings.xml
  *
  * Copyright (c) 2000-2012 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Default conference settings.
  *
  * $Id$
  -->

<!DOCTYPE conference_settings [
	<!ELEMENT conference_settings (setting+)>
	<!ELEMENT setting (name, value)>
	<!ATTLIST setting type (int|string|object|bool) #REQUIRED>
	<!ATTLIST setting locale (0|1) #REQUIRED>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT value (#PCDATA | array)*>
	<!ELEMENT element (#PCDATA | array)*>
	<!ATTLIST element key CDATA #IMPLIED>
	<!ELEMENT array (element+)>
]>

<conference_settings>
	<setting type="int" locale="0">
		<name>numPageLinks</name>
		<value>10</value>
	</setting>
	<setting type="int" locale="0">
		<name>itemsPerPage</name>
		<value>25</value>
	</setting>
	<setting type="string" locale="1">
		<name>copyrightNotice</name>
		<value>{translate key="default.conferenceSettings.copyrightNotice"}</value>
	</setting>
	<setting type="string" locale="1">
		<name>privacyStatement</name>
		<value>{translate key="default.conferenceSettings.privacyStatement"}</value>
	</setting>
	<setting type="string" locale="1">
		<name>archiveAccessPolicy</name>
		<value>{translate key="default.conferenceSettings.archiveAccessPolicy"}</value>
	</setting>
	<setting type="string" locale="1">
		<name>authorSelfArchivePolicy</name>
		<value>{translate key="default.conferenceSettings.authorSelfArchivePolicy"}</value>
	</setting>
	<setting type="string" locale="1">
		<name>readerInformation</name>
		<value>{translate key="default.conferenceSettings.forReaders"}</value>
	</setting>
	<setting type="string" locale="1">
		<name>authorInformation</name>
		<value>{translate key="default.conferenceSettings.forAuthors"}</value>
	</setting>
	<setting type="string" locale="1">
		<name>lockssLicense</name>
		<value>{translate key="default.conferenceSettings.lockssLicense"}</value>
	</setting>

	<setting type="object" locale="0">
		<name>supportedLocales</name>
		<value>
			<array>
				<element>{$primaryLocale}</element>
			</array>
		</value>
	</setting>
	<setting type="object" locale="0">
		<name>supportedFormLocales</name>
		<value>
			<array>
				<element>{$primaryLocale}</element>
			</array>
		</value>
	</setting>
	<setting type="object" locale="0">
		<name>supportedSubmissionLocales</name>
		<value>
			<array>
				<element>{$primaryLocale}</element>
			</array>
		</value>
	</setting>
	<setting type="string" locale="0">
		<name>paymentMethodPluginName</name>
		<value>ManualPayment</value>
	</setting>

	<setting type="bool" locale="0">
		<name>rtAbstract</name>
		<value>true</value>
	</setting>
	<setting type="bool" locale="0">
		<name>rtCaptureCite</name>
		<value>true</value>
	</setting>
	<setting type="bool" locale="0">
		<name>rtViewMetadata</name>
		<value>true</value>
	</setting>
	<setting type="bool" locale="0">
		<name>rtSupplementaryFiles</name>
		<value>true</value>
	</setting>
	<setting type="bool" locale="0">
		<name>rtPrinterFriendly</name>
		<value>true</value>
	</setting>
	<setting type="bool" locale="0">
		<name>rtAuthorBio</name>
		<value>true</value>
	</setting>
	<setting type="bool" locale="0">
		<name>rtDefineTerms</name>
		<value>true</value>
	</setting>
	<setting type="bool" locale="0">
		<name>rtAddComment</name>
		<value>true</value>
	</setting>
	<setting type="bool" locale="0">
		<name>rtEmailAuthor</name>
		<value>true</value>
	</setting>
	<setting type="bool" locale="0">
		<name>rtEmailOthers</name>
		<value>true</value>
	</setting>
	<setting type="bool" locale="1">
		<name>metaCitations</name>
		<value>1</value>
	</setting>
</conference_settings>
