<?xml version="1.0" encoding="UTF-8"?>
<!--
  * version.xml
  *
  * Copyright (c) 2000-2010 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * OCS version information.
  *
  * $Id$
  -->

<!DOCTYPE version [
	<!ELEMENT version (application, release, tag, date, info, package, patch*)>
	<!ELEMENT application (#PCDATA)>
	<!ELEMENT release (#PCDATA)>
	<!ELEMENT tag (#PCDATA)>
	<!ELEMENT date (#PCDATA)>
	<!ELEMENT info (#PCDATA)>
	<!ELEMENT package (#PCDATA)>
	<!ELEMENT patch (#PCDATA)>
		<!ATTLIST patch
			from CDATA #REQUIRED>
]>

<version>
	<application>ocs2</application>
	<release>2.1.2</release>
	<tag>ocs-2_1_2-1</tag>
	<date>2009-07-19</date>
	<info>http://pkp.sfu.ca/ocs/</info>
	<package>http://pkp.sfu.ca/ocs/download/ocs-2.1.2-1.tar.gz</package>
	<patch from="2.0.0.0">http://pkp.sfu.ca/ocs/download/patch/ocs-2.0.0-1_to_2.1.2.patch.gz</patch><!-- OCS 2.0.0.1 is marked in DB as 2.0.0.0. -->
	<patch from="2.1.0.0">http://pkp.sfu.ca/ocs/download/patch/ocs-2.1.0-0_to_2.1.2.patch.gz</patch>
	<patch from="2.1.0.1">http://pkp.sfu.ca/ocs/download/patch/ocs-2.1.0-1_to_2.1.2.patch.gz</patch>
	<patch from="2.1.1.0">http://pkp.sfu.ca/ocs/download/patch/ocs-2.1.1_to_2.1.2.patch.gz</patch>
	<patch from="2.1.1.1">http://pkp.sfu.ca/ocs/download/patch/ocs-2.1.1-1_to_2.1.2.patch.gz</patch>
	<patch from="2.1.1.2">http://pkp.sfu.ca/ocs/download/patch/ocs-2.1.1-2_to_2.1.2.patch.gz</patch>
</version>
